baseURL = "https://wastenot.cz/"
languageCode = "en-us"
title = "Infinity | Comming Soon Hugo Template By Themefisher"
theme = "infinity-hugo"
removePathAccents = true
[params]

# HTML before the closing </head>
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "DOMŮ"
about = "O NÁS"
service = "NAŠE SLUŽBY"
contact = "KONTAKT"

# Hero Area
[params.hero]
enable            = true
bg                = "images/header-bg.jpg"
title             = "NEPLÝTVEJ... ZUŽITKUJ!"
subtitle          = ""
btnText           = "NAŠE SLUŽBY"

# counter
disableCountdown  = false
countdownYear = "2020"
countdownMonth = "12"
countdownDay  = "31"

# About Section
[params.about]
enable      = true
heading     = ""
description = [
"Júlia a Tereza, kterým není jedno co se kolem nich děje a rády posouvají věci kupředu. Každodenní rozhodnutí kohokoliv z nás ovlivňuje svět, ve kterém žijeme, a budou žít další generace. Ano, každý z nás může jako jednotlivec změnit svět, ale my bychom se rády zaměřili na firmy a korporace, které mají dopad na životní prostředí mnohonásobně větší a i malá změna může mít daleko větší dosah.",
]



[[params.about.sliderItem]]
image   = "images/about/1.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"
[[params.about.sliderItem]]
image   = "images/about/3.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"


# Service Section
[params.service]
enable      = true
title       = "NAŠE SLUŽBY"
subtitle    = ""

[[params.service.serviceRow]]
color = "#88e8e4"

[[params.service.serviceRow.seviceItem]]
description = "revize stávajícího systému odpadového hospodářství"
delay   = "0s"

[[params.service.serviceRow.seviceItem]]
description = "zmapování toku jednotlivých druhů odpadu od místa jejich vzniku až po předání k likvidaci"
delay   = "0.2s"

[[params.service.serviceRow.seviceItem]]
description = "průběžná evidence odpadů"
delay   = "0.6s"

[[params.service.serviceRow.seviceItem]]
description = "zpracování ročního hlášení o produkci a nakládání s odpady a výkazu o odpadech a druhotných surovinách"
delay   = "0.8s"

############
# NEXT ROW #
############

[[params.service.serviceRow]]
color="#88bbe8"

[[params.service.serviceRow.seviceItem]]
description = "posouzení stavu systému vzhledem k požadavkům ISO 14001:2015"
delay   = "0.3s"

[[params.service.serviceRow.seviceItem]]
description = "navržení postupu implementace a nastavení systému dle požadavků normy"
delay   = "0.8s"

[[params.service.serviceRow.seviceItem]]
description = "realizace situačního auditu jako forma kontroly připravenosti společnosti na certifikaci"
delay   = "1s"

[[params.service.serviceRow.seviceItem]]
description = "účast na certifikačním auditu účast na certifikačním auditu účast na certifikačním auditu"
delay   = "1.2s"


############
# NEXT ROW #
############

[[params.service.serviceRow]]
color="#88e8b5"

[[params.service.serviceRow.seviceItem]]
description = "návrh environmentální vize a podmínek pro její naplnění"
delay   = "0.4s"


[[params.service.serviceRow.seviceItem]]
description = "návrh a podpora realizace environmentálních projektů"
delay   = "1s"

[[params.service.serviceRow.seviceItem]]
description = "poradenství a účast na výběrovém řízení ideálního partnera zajišťujícího služby v oblasti fyzické likvidace odpadů"
delay   = "1.2s"

[[params.service.serviceRow.seviceItem]]
description = "BLA BLA BLA BLA BLA"
delay   = "1.5s"

# Call to Action Section
[params.cta]
enable      = true
bg          = "images/call-to-action.jpg"
title       = "Subscribe to our mailing list"
subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

[params.contact]
enable      = true
title       = "KONTAKTUJTE NÁS"
subtitle    = ""
